### ISSUE TITLE
GTK Warnings: "Theme parsing error"

### ISSUE THREAD

**Issue by charlie-haley** [fourstepper/wofi-wifi-menu#3]
Investigate GTK warnngs below: 
```(wofi:16635): Gtk-WARNING **: 17:11:52.051: Theme parsing error: <data>:7:10: 'height' is not a valid property name```

![image](https://user-images.githubusercontent.com/27928201/80734335-e9fda400-8b06-11ea-8012-ec4cd2eb6779.png)

**Comment by fourstepper** [comment]
I am starting to think if this is not related to missing entries from the LIST variable

![image](https://user-images.githubusercontent.com/49439044/80736599-a5780580-8b12-11ea-96f7-db34ed0f62f2.png)

Could you please send me your output of `nmcli --fields "$FIELDS" device wifi list | sed '/^--/d'` ?

It would even make sense in the context of the code and the error

```
LIST=$(nmcli --fields "$FIELDS" device wifi list | sed '/^--/d')
# For some reason wofi always approximates character width 2 short... hmmm
RWIDTH=$(($(echo "$LIST" | head -n 1 | awk '{print length($0); }')*10))
```

**Comment by charlie-haley** [comment]
Obscured some SSID's for obvious reasons, but that's the output of `$LIST` if I `echo $LIST` in the script 

```
SSID SECURITY BARS RandomNetwork_2BA186 -- ▂▄▆_ Anotherssid WPA2 ▂▄__ fj2303 WPA2 ▂▄__ morewifinetworks WPA2 ▂▄__ Living Room TV.v -- ▂▄__ BTWifi-with-FON -- ▂___ PLUSNET-H82F WPA2 ▂___ DEN WPA1 WPA2 ▂___ BTWifi-X WPA1 WPA2 802.1X ▂___ SKY5A4E7 WPA2 ▂___ BTHomeSpot-CPZ WPA1 WPA2 ▂___ PLUSNET-H82F WPA2 ▂___ EE-s7rkac WPA1 WPA2 ▂___ EE-Hub-sT6d WPA2 ▂___ 5GHz-EE-s7rkac WPA1 WPA2 ▂___ SKY5A4E7 WPA2 ▂___
```

**Comment by fourstepper** [comment]
Alright. This might then not be an issue after all. I also realize that the above screenshot I've sent made no sense, but I have tested it in the script as well and am sure that `echo $LIST` doesn't output anything.

I will buy some basic USB wifi adapter for my PC asap for me to be able to test and contribute fully
